### PR TITLE
Added script for starting mapintel

### PR DESCRIPTION
**Pull request by stuartgo**
# Pull Request Guide

## Checklist 

Please check the following:

- [x ] You have checked the [Pull Request guidelines](https://github.com/NOVA-IMS-Innovation-and-Analytics-Lab/MapIntel/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for bug fixes or new features have been added.
- [ ] Docs have been added or updated.

## Type

What kind of change does this Pull Request introduce?

- [ ] fix: Bug fix.
- [x] feat: New feature implementation.
- [ ] build: Build system or external dependencies changes.
- [ ] ci: CI configuration files and scripts changes.
- [ ] docs: Documentation improvements.
- [ ] perf: Performance improvement.
- [ ] refactor: Code refactor.
- [ ] test: Test additions or corrections.
- [ ] other

## Current behaviour

Describe the current behaviour or provide a link to an issue.

## What is the new behavior?

Describe the new behaviour.

## Does this Pull Request introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

Provide any other information.

### CODE REVIEW

**Review by georgedouzas — COMMENTED** [review]
I suggest the following steps:

1. Move the functions that wrap the models to the corresponfing service.
2. Use [click](https://click.palletsprojects.com/en/8.1.x/) to create a `mapintel start` command.
3. The we will think about the `mapintel init` command.

**Review by georgedouzas — COMMENTED** [review]
I have added some stuff. Think about the API, requirements etc of the CLI.

**Comment by georgedouzas** [comment]
You need also to `git pull --rebase` from the master.

**Comment by stuartgo** [comment]
> 1. unctions that wrap the models to the corresponfing service.

The wrappers arent universal though, shouldnt the specific code for statring the app be held separate to the more general code that includes the services?

**Comment by stuartgo** [comment]
image
image

Do you know why this is happening. It seems to cause an error in an autogenerated file in the venv, but without that file nothing happens when I run `mapintel start`. The second image is the file in the venv

**Comment by stuartgo** [comment]
Not sure I understood, if I run `mapintel start` now, with this code, shouldnt "hello!" be printed?
image

**Comment by georgedouzas** [comment]
> Not sure I understood, if I run `mapintel start` now, with this code, shouldnt "hello!" be printed? image

No, unless you have registered somehow `mapintel` as shell command. For example it can be done through `console_scripts`.

**Comment by georgedouzas** [comment]
It would be nice of course not to include the `python src/cli.py` part. This can be done using `console_scripts`.

**Comment by georgedouzas** [comment]
Basically wait I will fix it, test it and update the branch.

**Comment by georgedouzas** [comment]
I tested and it works as expected with the commands `python src/mapintel/cli.py init` or `python src/mapintel/cli.py start`.

**Comment by georgedouzas** [comment]
Sorry I was writing the wrong path before. We would obviously prefer to avoid the `python src/mapintel/cli.py` part and replace it with `mapintel` command. It can be done through `console_scripts`. Dont worry about it at the moment.

**Comment by stuartgo** [comment]
Ok now I have them running, I have to leave now, but I should be able to finish it tomorrow

**Comment by georgedouzas** [comment]
Why do we need the file to be pushed to the repo?

**Comment by stuartgo** [comment]
For the initial data, but I guess it could be fetched from somewhere else

**Comment by georgedouzas** [comment]
You should have them locally and provide them through the command `mapintel init` command.

**Comment by stuartgo** [comment]
ahh yes sorry ofc

**Comment by stuartgo** [comment]
I cant figure out how to pass a list and lsit of dicts in cli, I tried in python. Shouldnt json.dumps format it correctly? It doesnt like that there are multiple string I think.
image

**Comment by georgedouzas** [comment]
Why don't you pass the path to the json file that contains the documents?

**Comment by stuartgo** [comment]
Now it should work, not sure why it complains about conflicts,all those files should just be replaced with the new ones

**Review by georgedouzas — CHANGES_REQUESTED** [review]
Could you cleanup the code?

1. Remove commented out code
2. Move the helper functions to appropriate files (maybe in src?)
3. Generally avoid spawining new process from the scripts.  Can't we use the Python API.
4. Consider also the case when the app is not initialized but we try to start it etc

**Comment by stuartgo** [comment]
Yes sure, but for 3. I am not sure how to do it? As you need the API running while you populate it with models.

**Comment by georgedouzas** [comment]
I mean, instead of spawning a process and run some CLI commands, can't we do the same through the Python API?

**Comment by stuartgo** [comment]
For both the start and init or only the init?

**Comment by georgedouzas** [comment]
For both of them.

**Comment by stuartgo** [comment]
The issue I am having is that when I try to start the API it stops running the following code, it waits until the API is stopped and then runs the following code.

**Comment by georgedouzas** [comment]
Ok I would say to do your best to cleanup the repo and we will see how to handle the remaining issues.

**Comment by stuartgo** [comment]
Regarding moving the functions to appropriate files, I don't know if having it in the source make sense as its somewhat separate to the rest of the functionality. I can split it into smaller files if that makes it more manageable to understand?

**Comment by georgedouzas** [comment]
`pdm formatting`

**Comment by georgedouzas** [comment]
Dont worry about the rest. Please push it to check it.

**Comment by stuartgo** [comment]
I forgot to rebase.... Sorry, how do I avoid creating conflicts?

**Comment by georgedouzas** [comment]
Try `git pull --rebase origin start_task` from your local branch `start_task`. Then `git rebase --skip` in each conflict.

**Comment by stuartgo** [comment]
Should I commit my changes first, it says it cannot rebase

**Comment by georgedouzas** [comment]
Even better `git stash`. Delete your local `start_task` branch and `git switch start_task` to recreate it from remote. Then `git stash pop`.

**Comment by stuartgo** [comment]
Wouldnt I lose my local changes if I stash and then switch?

**Comment by georgedouzas** [comment]
No but you can rename your local branch just to make sure you do not loose your work :p

**Comment by stuartgo** [comment]
Ok should have pushed the correct code now

**Comment by georgedouzas** [comment]
I have made some changes. Please check that the implementation is still correct.

**Comment by stuartgo** [comment]
I didnt test it, but the changes seem to be all just code reformatting so it should be good. It doesn't work currently though as the thread thing in the `start` command is still an issue

**Pull request closed without merging**
